PREFIX dcam: <http://purl.org/dc/dcam/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
INSERT DATA
{
      <%s> rdfs:domain|dcam:domainIncludes|schema:domainIncludes <%s> .
}
