PREFIX rr: <http://www.w3.org/ns/r2rml#>
DELETE { ?subject rr:termType ?currentTermType  }
INSERT { ?subject rr:termType %s }
WHERE {
    SELECT ?subject ?currentTermType
    WHERE {
          ?subject ?p ?o .
          OPTIONAL { ?subject rr:termType ?currentTermType }
          FILTER(str(?subject) = "%s").
    }
}