PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX prov: <http://www.w3.org/ns/prov#>
SELECT ?property (GROUP_CONCAT(?commentProperty ; separator=' ') AS ?comment)
WHERE {
  GRAPH <%s> {
  ?property a ?type .
  OPTIONAL { ?property  rdfs:comment|skos:definition|prov:definition ?commentProperty . }
  FILTER(CONTAINS (LCASE(STR(?type)), 'property'))
  # FILTER(?type IN (rdf:Property, owl:AnnotationProperty, owl:ObjectProperty, owl:DataProperty, owl:FunctionalProperty, owl:DatatypeProperty))
  }
}
GROUP BY ?property