PREFIX rr: <http://www.w3.org/ns/r2rml#>
DELETE { ?subject rr:termType %s .  }
WHERE {
    SELECT ?subject
    WHERE {
          ?subject rr:termType %s .
          FILTER(str(?subject) = "%s").
        }
}