PREFIX rr: <http://www.w3.org/ns/r2rml#>
DELETE { ?subject rr:datatype ?datatype .  }
WHERE {
SELECT ?subject ?datatype
WHERE {
      ?subject rr:datatype ?datatype.
      FILTER(str(?subject) = "%s").
    }
}