PREFIX rr: <http://www.w3.org/ns/r2rml#>
SELECT ?pom
WHERE {
  OPTIONAL { ?tripleMap rr:predicateObjectMap ?pom . ?pom rr:predicateMap|rr:predicate ?predicate . }
  OPTIONAL { ?tripleMap rr:predicateObjectMap ?pom . ?pom rr:objectMap|rr:object ?om . }
  FILTER(!BOUND(?predicate) || !BOUND(?om))
}