PREFIX rr: <http://www.w3.org/ns/r2rml#>
SELECT ?datatype ?om
WHERE {
     ?subject rr:predicateObjectMap ?pom .
     ?pom rr:objectMap ?om .
     ?om rr:datatype ?datatype .
     FILTER(!isIRI(?datatype))
}