PREFIX rr: <http://www.w3.org/ns/r2rml#>
PREFIX rml: <http://semweb.mmlab.be/ns/rml#>
SELECT DISTINCT ?tripleMap
WHERE {
  ?tripleMap  rr:predicateObjectMap|rr:subjectMap ?object .
  FILTER NOT EXISTS { ?tripleMap  rr:logicalTable|rml:logicalSource ?logicalSource . }
}