PREFIX rr: <http://www.w3.org/ns/r2rml#>
INSERT { ?joinCondition rr:child "%s" }
WHERE {
SELECT ?joinCondition
WHERE {
      ?subject rr:joinCondition ?joinCondition.
      FILTER(str(?joinCondition) = "%s").
    }
}