PREFIX rr: <http://www.w3.org/ns/r2rml#>
DELETE { ?subject ?predicate %s  }
INSERT { ?subject ?predicate %s }
WHERE {
SELECT ?subject ?predicate
WHERE {
      ?subject ?predicate %s .
      FILTER(str(?subject) = "%s").
    }
}