PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dct: <http://purl.org/dc/terms/>
ASK {
    GRAPH <%s> { ?subject a owl:Ontology;
       dc:creator|dc:publisher|dct:creator|dct:contributor|dcterms:publisher|dc:title|dc:description|rdfs:comment|foaf:maker ?label .
    }
}

